language: c
os:
    - linux
      #- osx

env:
  global:
    - GOPATH=~
    - DOTPATH=~/.dotfiles

install:
    - curl -L https://github.com/bjornrun/dotfiles-3/archive/master.tar.gz | bash

before_script:
    - cd $(dotpath)

script:
    - make --silent test
